### ISSUE TITLE
Question about improvements, etc

### ISSUE THREAD

**Issue by gesslar** [lnguyenfx/simplemud#3]
Is the idea that this should be as faithful to the source material as possible, or if I wanted to actual work on it as a base, should I send pull requests to make it a viable product or just keep my fork to myself?

**Comment by lnguyenfx** [comment]
The goal of this repository is to serve as a learning tool for anyone who is interested from writing a rudimentary MUD server from scratch; hence the name, "SimpleMUD". There is certainly no restrictions that it should be as close the source material as possible. If you feel that the changes you plan to make aligns with the goal of teaching MUD server programming to beginners, then I would highly encourage and appreciate your contributions. If, however, you feel that your changes would make the codebase more specialized and complex to the point that the average beginning programmer cannot grasp, then it may be better to keep your codebase as a fork and even rename it to something more suitable other than "SimpleMUD" if you want. 

It has been more than two years since I made the project public and you are the first to reach out to contribute, so thanks so much.
